### ISSUE TITLE
undefined method `attached'

### ISSUE THREAD

**Issue by picharras** [ksylvest/attached#1]
Hello, I have this error when migrating on rails 3.1.1

Run:

rake db:migrate
undefined method `attached' for #ActiveRecord::ConnectionAdapters::TableDefinition:0xb6c97cf8

My code is:

class CreateVideos < ActiveRecord::Migration
  def self.up
    create_table :videos do |t|
      t.string :title
      t.text :description
      t.attached :video_hd

```
  t.timestamps
end
```

  end

  def self.down
    drop_table :videos
  end

end

**Comment by ksylvest** [comment]
Sorry the read me had a bug in it. In your migration (note the change of `t.attached` to `t.attachment`) do:

```
class CreateVideos < ActiveRecord::Migration
  def self.up
    create_table :videos do |t|
      t.string :title
      t.text :description
      t.attachment :video_hd

      t.timestamps
    end
  end

  def self.down
    drop_table :videos
  end
end
```

Let me know if this fixes the problem.

**Comment by ksylvest** [comment]
As an aside, you can see a full example application that uses the library and is specific for videos here:

https://github.com/ksylvest/zencodeit

**Comment by ksylvest** [comment]
Closing after fixing documentation.
